import type { Metadata } from 'next';

import { ThemeProvider } from '@/components/providers/theme';

import '../styles/globals.scss';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className="bg-background text-foreground antialiased">
                <ThemeProvider>{children}</ThemeProvider>
            </body>
        </html>
    );
}
